//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR_10_GNE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Excursion
    {
        public int id { get; set; }
        public string name { get; set; }
        public string guide { get; set; }
        public int hall { get; set; }
        public int cost { get; set; }
        public int number_of_visitors { get; set; }
        public int duration { get; set; }
    
        public virtual Halls Halls { get; set; }
    }
}
